---
book_filename: "bookdownproj"
output_dir: docs
delete_merged_file: true
edit: https://github.com/CarolitaE/DAP-2021/edit/master/%s
view: https://github.com/CarolitaE/DAP-2021/blob/main/%s
language:
  ui:
    chapter_name: "Chapter 2 "
---

# Raw Data & Methods 2021 {#cross}

## Bulk Density

Bulk density was sampled in field using standard 5cm bulk density rings for the 0-5cm and 5-10 cm depths. A madera soil sampling probe (Madera industrial Inc. Lincoln,NE) was used to measure the 10-20cm depths. The giddings probe volume was used to calculate BD for the 20-80cm depths.

## Total Carbon and Nitrogen

-   Total carbon (TC) and total Nitrogen (TN) were analyzed using LECO at the USDA ARS laboratory located in Fort Collins CO. Samples were loaded into ceramic boats with a specific samples mass, loaded into the LECO, and their % Carbon and % Nitrogen values are applied to the sample mass.
-   Total C and N values have to then be applied to BD in order to get %Nitrogen T/ha. Using the following calculation
    -   %N/g X BD X Depth X 100 (unit conversion factor)

## Inorganic Carbon

Inorganic carbon is analyzed using the pressure calcimeter method created by Sherrod et al. This methodology measure %Calcium carbonate that you can further calculate to get %inorganic Carbon

%IC will be subtracted from %TC in order to get %OC

## Load Raw Data

```{r}
library(tidyverse)
library(plotly)
library(ggplot2)
library(ggplotgui)
library(readxl)
library(dplyr)
library(tidyr)
library(bookdown)

DAP_ALL_RAW<- read_xlsx("/Users/carolitalanders/Documents/Grad /DAP/DONT EDIT/DAP_2021_all_data.xlsx")
```
